### ISSUE TITLE
Use DoltLab in a server without Internet access

### ISSUE THREAD

**Issue by marceloavilaoliveira** [dolthub/doltlab-issues#94] opened 2024-08-13 18:12 UTC
Hi,

We are using DoltLab 2.3.0 in a server without Internet access and when DoltLab tries to create a job we receive the following error:

creation of job failed after 5 retries: final error: 
Error response from daemon:

`Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

Is it possible to use DoltLab in a server without access to public.ecr.aws? Is there a way to workaround this issue?

Thanks a lot.

**Comment by coffeegoddd** [comment] 2024-08-14 17:04
Hey @marceloavilaoliveira,

I believe the workaround for being able to use the DoltLab service images i.e. `public.ecr.aws` would be to use [docker image save](https://docs.docker.com/reference/cli/docker/image/save/) to store them on a usb drive, then load them with [docker image load](https://docs.docker.com/reference/cli/docker/image/load/).

**Comment by marceloavilaoliveira** [comment] 2024-09-05 17:21
Hi @coffeegoddd,

The docker workaround did not work as expected. To resolve the issue we had to allow the access to the following URLs:

- public.ecr.aws
- api.github.com
- eventsapi.dolthub.com

This was not our original desire but the application seems to be working now.

**Comment by coffeegoddd** [comment] 2024-09-05 17:30
@marceloavilaoliveira Ah, thanks for the update on this. I believe our plan is to support full offline (no egress required) for DoltLab Enterprise only. Tracking issue here https://github.com/dolthub/doltlab-issues/issues/95

**Comment by coffeegoddd** [comment] 2024-09-06 17:55
@marceloavilaoliveira may I ask how you found the need to allow access `api.github.com`? From my investigation/testing I'm not able to reproduce the need to allow access to that url. It is used in DoltHub, but should not be required for DoltLab.

**Comment by coffeegoddd** [comment] 2024-09-20 22:19
@marceloavilaoliveira [DoltLab v2.3.3](https://github.com/dolthub/doltlab-issues/releases/tag/v2.3.3) is out now and supports running without egress traffic allowed on the host.

To do so you need to disable usage metrics by setting `metrics_disabled: true` in the `installer_config.yaml`, this will stop calls to `eventsapi.dolthub.com`.

I found that running `dolt version` from within the Jobs was calling to `api.github.com`, and this has been removed.

Finally, we now provide the service images to download, so they do not need to be pulled from `public.ecr.aws`. For DoltLab v2.3.3, download [this zip file](https://doltlab-releases.s3.amazonaws.com/linux/amd64/doltlab-service-images-v2.3.3.zip).

Unzip the file on your DoltLab host. Inside you will see `tar` files for each service DoltLab depends on. For example, this is the `doltlabapi` service `tar`: `dolthubapi-server-v2.3.3.tar`.

For each file, run the `docker load` command to load the image onto the DoltLab host:
```bash
docker load < dolthubapi-server-v2.3.3.tar
```

After load the images, you will be able to see them in the output of `docker image ls -a`.

Finally, start DoltLab, and it will be able to use the images.

Closing this issue for now, please reach out if you encounter any more issues.

**Closed as completed by coffeegoddd** 2024-09-20 22:19 UTC

**Comment by marceloavilaoliveira** [comment] 2024-09-23 11:14
Hi @coffeegoddd 

Sorry for the delay in responding, we really had busy days from our side.

Thanks a lot for your support, we'll try to follow your recommendations. 

Best regards.
